// src/ValidationSection/ValidationSection.tsx
import { useState } from 'react';
import { useHashes } from '../common/hooks/useHashes';
import { DropZone } from '../DropZone';
import type { FileData } from '../HashesTable';
import { ProgressCounter } from '../ProgressCounter';
import type { Manifest } from '../types/Manifest';
import { ValidationTable, type ValidationResult } from '../ValidationTable';
import { useManifest } from './useManifest';

import styles from './ValidationSection.module.css';

const compareHashes = (manifest: Manifest, files: FileData[]): ValidationResult[] => {
  const result: ValidationResult[] = [];
  const manifestMap = new Map(manifest.files.map((file) => [file.name, file.hash]));

  files.forEach((file) => {
    if (!manifestMap.has(file.name)) {
      result.push({
        name: file.name,
        status: {
          ok: false,
          message: 'Файл не найден в манифесте',
        },
      });
    } else {
      const isHashValid = manifestMap.get(file.name) === file.hash;
      result.push({
        name: file.name,
        status: {
          ok: isHashValid,
          message: isHashValid ? '✅ Совпадает' : '⚠️ Изменён',
        },
        expectedHash: manifestMap.get(file.name),
        hash: file.hash,
      });
    }
  });

  return result;
};

export const ValidationSection = () => {
  const { currentFile, handleFiles, isHashing, proceededFiles, totalFilesCount } = useHashes();
  const { handleManifest, manifestContent, manifestHash } = useManifest();
  const [validationResult, setValidationResult] = useState<ValidationResult[] | null>(null);
  const [expectedHash, setExpectedHash] = useState('');

  const onDropFiles = async (files: FileList) => {
    const hashes = await handleFiles(files);
    if (manifestContent) {
      const result = compareHashes(manifestContent, hashes);
      setValidationResult(result);
    }
  };

  return (
    <div>
      <DropZone
        key="manifest"
        id="manifest"
        dropLabel="Перетащите проверяемый манифест (JSON) сюда или"
        onDrop={handleManifest}
        accept=".json"
        buttonLabel="Выбрать файл"
      />
      {manifestContent && (
        <>
          <p>✅ Манифест загружен. Найдено файлов: {manifestContent.files.length}</p>
          <p>Хэш манифеста: {manifestHash}</p>
          <div className={styles.inputGroup}>
            <label htmlFor="expectedManifestHash" className={styles.hashLabel}>
              Ожидаемый хэш манифеста:{' '}
            </label>
            <input
              type="text"
              id="expectedManifestHash"
              placeholder="Вставьте хэш"
              className={styles.hashInput}
              onChange={(event) => setExpectedHash(event.target.value)}
            />
            {expectedHash && expectedHash === manifestHash && (
              <p>✅ Хэш сумма манифеста совпадает</p>
            )}
            {expectedHash && expectedHash !== manifestHash && (
              <p>⚠️ Хэш сумма манифеста изменена</p>
            )}
          </div>
        </>
      )}
      {manifestContent && (
        <DropZone
          key="filesForValidation"
          id="filesForValidation"
          dropLabel="Перетащите проверяемые файлы сюда или"
          accept="image/*,video/*"
          multiple
          onDrop={onDropFiles}
        />
      )}
      {isHashing ||
        (!!proceededFiles.length && (
          <ProgressCounter current={currentFile} total={totalFilesCount} />
        ))}
      {!!validationResult?.length && <ValidationTable files={validationResult} />}
    </div>
  );
};

// src/components/ValidationSection.svelte
<script lang="ts">
  import { compareHashes } from '../common/utils/compareHashes';
  import type { ValidationResult } from '../types/ValidationResult';
  import DropZone from './DropZone.svelte';
  import ProgressCounter from './ProgressCounter.svelte';
  import { useHashes } from './useHashes.svelte';
  import { useManifest } from './useManifest.svelte';
  import ValidationTable from './ValidationTable.svelte';

  const hashes = useHashes();
  const manifest = useManifest();
  let validationResult = $state<ValidationResult[]>();
  let expectedHash = $state<string>();

  const onDropFiles = async (files: FileList) => {
    await hashes.handleFiles(files);
    if (manifest.manifestContent && hashes.proceededFiles.length) {
      const result = compareHashes(manifest.manifestContent, hashes.proceededFiles);
      validationResult = result;
    }
  };
</script>

<div>
  <DropZone
    id="manifest"
    dropLabel="Перетащите проверяемый манифест (JSON) сюда или"
    onDrop={manifest.handleManifest}
    accept=".json"
    buttonLabel="Выбрать файл"
  />

  {#if manifest.manifestContent}
    <p>✅ Манифест загружен. Найдено файлов: {manifest.manifestContent.files.length}</p>
    <p>Хэш манифеста: {manifest.manifestHash}</p>
    <div class="input-group">
      <label for="expectedManifestHash" class="hash-label">
        Ожидаемый хэш манифеста:{' '}
      </label>
      <input
        type="text"
        id="expectedManifestHash"
        placeholder="Вставьте хэш"
        class="hash-input"
        bind:value={expectedHash}
      />

      {#if expectedHash && expectedHash === manifest.manifestHash}
        <p>✅ Хэш сумма манифеста совпадает</p>
      {:else if expectedHash && expectedHash !== manifest.manifestHash}
        <p>⚠️ Хэш сумма манифеста изменена</p>
      {/if}
    </div>

    <DropZone
      id="filesForValidation"
      dropLabel="Перетащите проверяемые файлы сюда или"
      multiple
      onDrop={onDropFiles}
    />
  {/if}

  {#if hashes.isHashing || hashes.proceededFiles.length > 0}
    <ProgressCounter current={hashes.processedFilesCount} total={hashes.totalFilesCount} />
  {/if}

  {#if validationResult?.length}
    <ValidationTable files={validationResult} />
  {/if}
</div>

<style>
  .input-group {
    margin-bottom: 16px;
    max-width: 100%;
  }

  .hash-label {
    margin-bottom: 8px;
    display: block;
  }

  .hash-input {
    width: 100%;
    padding: 10px;
    border: 1px solid #ccc;
    border-radius: 8px;
    font-family: monospace;
    font-size: 0.85rem;
  }
</style>
