// src/components/ValidationTable.svelte
<script lang="ts">
  import type { ValidationResult } from '../types/ValidationResult';

  interface ValidationTableProps {
    files: ValidationResult[];
  }

  let { files }: ValidationTableProps = $props();
</script>

<table>
  <thead>
    <tr>
      <th>Файл</th>
      <th>Статус</th>
      <th>Ожидаемый хэш</th>
      <th>Фактический хэш</th>
    </tr>
  </thead>
  <tbody>
    {#each files as file (file.name)}
      <tr>
        <td>{file.name}</td>
        <td class={file.status.ok ? 'status-ok' : 'status-fail'}>{file.status.message}</td>
        <td class="hash">{file.expectedHash ?? '-'}</td>
        <td class="hash">{file.hash ?? '-'}</td>
      </tr>
    {/each}
  </tbody>
</table>

<style>
  .hash {
    font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
    word-break: break-all;
    font-size: 0.85rem;
  }

  .status-ok {
    color: #198754;
    font-weight: bold;
  }

  .status-fail {
    color: #dc3545;
    font-weight: bold;
  }
</style>

// src/ValidationTable/ValidationTable.tsx
import type { FileData } from '../HashesTable';

import styles from './ValidationTable.module.css';

interface Status {
  ok?: boolean;
  message?: string;
}

export interface ValidationResult extends FileData {
  expectedHash?: string;
  status: Status;
}

interface ValidationTableProps {
  files: ValidationResult[];
}

export const ValidationTable = (props: ValidationTableProps) => {
  const { files } = props;

  return (
    <table>
      <thead>
        <tr>
          <th>Файл</th>
          <th>Статус</th>
          <th>Ожидаемый хэш</th>
          <th>Фактический хэш</th>
        </tr>
      </thead>
      <tbody>
        {files.map((file) => {
          return (
            <tr key={file.name}>
              <td>{file.name}</td>
              <td className={file.status.ok ? styles.statusOk : styles.statusFail}>
                {file.status.message}
              </td>
              <td className={styles.hash}>{file.expectedHash ?? '—'}</td>
              <td className={styles.hash}>{file.hash ?? '—'}</td>
            </tr>
          );
        })}
      </tbody>
    </table>
  );
};
