// src/components/GenerationSection.svelte
<script lang="ts">
  import { useHashes } from '../utils/useHashes.svelte';
  import DropZone from './DropZone.svelte';
  import ProgressCounter from './ProgressCounter.svelte';
  import HashesTable from './HashesTable.svelte';

  const hashes = useHashes();
</script>

<div>
  <DropZone
    id="filesForGeneration"
    dropLabel="Перетащите фото/видео сюда или"
    multiple
    onDrop={hashes.handleFiles}
  />

  {#if hashes.isHashing || hashes.proceededFiles.length > 0}
    <ProgressCounter current={hashes.processedFilesCount} total={hashes.totalFilesCount} />
  {/if}

  {#if hashes.manifest?.url}
    <a href={hashes.manifest.url} download={hashes.manifest.fileName} class="download-link">
      💾 Скачать манифест (JSON)
    </a>
  {/if}

  {#if !!hashes.proceededFiles.length}
    <HashesTable filesData={hashes.proceededFiles} />
  {/if}

  {#if hashes.manifest}
    <div id="manifestHashBox" class="hash-box">
      <span class="hash-label">Хэш манифеста: </span>
      <span>{hashes.manifest.hash ?? hashes.manifest.error}</span>

      {#if hashes.manifest.hash}
        <button
          class="copy-button"
          onclick={() => navigator.clipboard.writeText(hashes.manifest?.hash ?? '')}
          title="Копировать хэш"
        >
          📋 Копировать
        </button>
      {/if}
    </div>
  {/if}
</div>

<style>
  .download-link {
    padding: 0.5rem 1rem;
    background: #0d6efd;
    color: white;
    border: none;
    border-radius: 6px;
    cursor: pointer;
    font-size: 1rem;
    text-decoration: none;

    &:hover {
      background: #0b5ed7;
    }

    &:disabled {
      opacity: 0.5;
      cursor: not-allowed;
    }
  }

  .hash-box {
    background: #f0f7ff;
    border: 1px solid #0d6efd;
    border-radius: 10px;
    padding: 12px;
    margin: 12px 0;
    word-break: break-all;
    font-family: ui-monospace, monospace;
    font-size: 0.85rem;
    position: relative;
  }

  .hash-label {
    font-weight: 600;
    color: #0d6efd;
    display: block;
    margin-bottom: 4px;
  }

  .copy-button {
    position: absolute;
    top: 8px;
    right: 8px;
    background: #0d6efd;
    color: white;
    border: none;
    border-radius: 6px;
    padding: 4px 8px;
    font-size: 0.75rem;
    cursor: pointer;
  }
</style>

// src/GenerationSection/GenerationSection.tsx
import { useEffect, useState } from 'react';
import { DropZone } from '../DropZone';
import { HashesTable } from '../HashesTable';
import { ProgressCounter } from '../ProgressCounter';
import { useHashes } from '../common/hooks/useHashes';
import type { Manifest } from '../types/Manifest';

import styles from './GenerationSection.module.css';
import { sha256 } from '../common/utils/sha256';

export const GenerationSection = () => {
  const { currentFile, handleFiles, isHashing, proceededFiles, totalFilesCount } = useHashes();
  const [manifestHash, setManifestHash] = useState('');

  const manifest: Manifest = {
    generated_at: new Date().toISOString(),
    tool: 'Sha256nnel',
    files: proceededFiles,
  };

  const manifestString = JSON.stringify(manifest, null, 2);
  const manifestBlob = new Blob([manifestString], { type: 'application/json' });
  const href = URL.createObjectURL(manifestBlob);
  const fileName = `manifest_${new Date().toISOString().slice(0, 10)}.json`;

  useEffect(() => {
    if (proceededFiles.length !== totalFilesCount) {
      setManifestHash('');
      return;
    }

    const computeManifestHash = async () => {
      try {
        const hash = await sha256(manifestBlob);
        setManifestHash(hash);
      } catch (error) {
        console.error('Ошибка при вычислении хэша:', error);
        setManifestHash('Ошибка при вычислении хэша');
      }
    };

    computeManifestHash();
  }, [proceededFiles]);

  return (
    <div>
      <DropZone
        key="filesForGeneration"
        id="filesForGeneration"
        dropLabel="Перетащите фото/видео сюда или"
        onDrop={handleFiles}
        accept="image/*,video/*"
        multiple
      />
      {(isHashing || proceededFiles.length > 0) && (
        <ProgressCounter current={currentFile} total={totalFilesCount} />
      )}
      {!!proceededFiles.length && !isHashing && (
        <a href={href} download={fileName} className={styles.downloadLink}>
          💾 Скачать манифест (JSON)
        </a>
      )}
      {!!proceededFiles.length && <HashesTable filesData={proceededFiles} />}

      {!isHashing && !!proceededFiles.length && (
        <div id="manifestHashBox" className={styles.hashBox}>
          <span className={styles.hashLabel}>Хэш манифеста: </span>
          <span>{manifestHash}</span>
          <button
            className={styles.copyButton}
            onClick={() => navigator.clipboard.writeText(manifestHash)}
            title="Копировать хэш"
          >
            📋 Копировать
          </button>
        </div>
      )}
    </div>
  );
};
